import pathfinderPackage from "mineflayer-pathfinder";
const {pathfinder,Movements,goals}=pathfinderPackage;
import {plugin as collectBlockPlugin} from "mineflayer-collectblock";
import {plugin as toolPlugin} from "mineflayer-tool";
const {GoalNear,GoalFollow}=goals;
const FOOD=["bread","cooked_beef","cooked_porkchop","cooked_chicken","cooked_mutton","cooked_salmon","cooked_cod","baked_potato","carrot","apple","beetroot"];
const DANGER=new Set(["creeper","zombie","skeleton","spider","cave_spider","enderman","witch","drowned","husk","stray","phantom","pillager","vindicator","evoker","ravager","silverfish","endermite"]);
export class GameController{
  constructor(bot,memory,config){this.bot=bot;this.memory=memory;this.config=config;bot.loadPlugin(pathfinder);bot.loadPlugin(collectBlockPlugin);bot.loadPlugin(toolPlugin);this.movements=null;this.home=null;this.following=null;this.busy=false;this.lastAction=null;}
  ready(){this.movements=new Movements(this.bot);this.bot.pathfinder.setMovements(this.movements);}
  state(){
    const p=this.bot.entity?.position;
    const entities=Object.values(this.bot.entities||{}).filter(e=>e?.position).slice(0,40).map(e=>({type:e.type,name:e.name||e.displayName||"",distance:p?+p.distanceTo(e.position).toFixed(1):null}));
    const blocks=p?this.bot.findBlocks({matching:b=>b&&b.name!=="air",maxDistance:10,count:50}).map(pos=>this.bot.blockAt(pos)?.name).filter(Boolean):[];
    return {position:p?{x:+p.x.toFixed(1),y:+p.y.toFixed(1),z:+p.z.toFixed(1)}:null,health:this.bot.health,food:this.bot.food,experience:this.bot.experience?.level||0,dimension:this.bot.game?.dimension,time:this.bot.time?.timeOfDay,rain:this.bot.isRaining,players:Object.keys(this.bot.players).slice(0,20),nearbyEntities:entities,nearbyBlocks:[...new Set(blocks)],inventory:this.bot.inventory.items().map(i=>({name:i.name,count:i.count}))};
  }
  say(msg){if(msg)this.bot.chat(String(msg).replace(/\s+/g," ").slice(0,240));}
  follow(name){const t=this.bot.players[name]?.entity;if(!t)return false;this.following=name;this.bot.pathfinder.setGoal(new GoalFollow(t,2),true);return true;}
  stop(){this.following=null;this.bot.pathfinder.setGoal(null);this.busy=false;}
  come(name){const p=this.bot.players[name]?.entity;if(!p)return false;this.following=null;this.bot.pathfinder.setGoal(new GoalNear(p.position.x,p.position.y,p.position.z,2));return true;}
  goto(x,y,z){if([x,y,z].some(v=>!Number.isFinite(Number(v))))return false;this.following=null;this.bot.pathfinder.setGoal(new GoalNear(Number(x),Number(y),Number(z),2));return true;}
  setHome(){if(this.bot.entity)this.home=this.bot.entity.position.clone();}
  goHome(){return this.home?this.goto(this.home.x,this.home.y,this.home.z):false;}
  async eat(){const item=this.bot.inventory.items().find(i=>FOOD.includes(i.name));if(!item)return false;try{await this.bot.equip(item,"hand");await this.bot.consume();this.lastAction="ate "+item.name;return true}catch{return false}}
  async collect(item,count=1){const wanted=String(item||"").toLowerCase();const n=Math.max(1,Math.min(32,Number(count)||1));const blocks=this.bot.findBlocks({matching:b=>b&&b.name.includes(wanted),maxDistance:64,count:n});if(!blocks.length)return false;try{this.busy=true;await this.bot.collectBlock.collect(blocks.map(p=>this.bot.blockAt(p)).filter(Boolean).slice(0,n));this.lastAction="collected "+wanted;return true}catch(e){this.memory.remember(this.config.owner,"failure","collect "+wanted+": "+e.message,3);return false}finally{this.busy=false}}
  async craft(item,count=1){const name=String(item||"").toLowerCase(),id=this.bot.registry.itemsByName[name]?.id;if(!id)return false;const recipes=this.bot.recipesAll(id,null,1,true);if(!recipes.length)return false;try{this.busy=true;await this.bot.craft(recipes[0],Math.max(1,Math.min(64,Number(count)||1)));this.lastAction="crafted "+name;return true}catch(e){this.memory.remember(this.config.owner,"failure","craft "+name+": "+e.message,3);return false}finally{this.busy=false}}
  async smelt(item,count=1){const furnace=this.bot.findBlock({matching:b=>b?.name==="furnace"||b?.name==="blast_furnace",maxDistance:24});if(!furnace)return false;const input=this.bot.inventory.items().find(i=>i.name===item),fuel=this.bot.inventory.items().find(i=>["coal","charcoal","oak_planks","spruce_planks","birch_planks","acacia_planks","jungle_planks","dark_oak_planks","mangrove_planks","cherry_planks"].includes(i.name));if(!input||!fuel)return false;try{const w=await this.bot.openFurnace(furnace);await w.putInput(input.type,null,Math.min(input.count,Number(count)||1));await w.putFuel(fuel.type,null,Math.min(fuel.count,8));await new Promise(r=>setTimeout(r,Math.min(30000,Math.max(4000,(Number(count)||1)*2200))));await w.takeOutput();w.close();this.lastAction="smelted "+item;return true}catch(e){this.memory.remember(this.config.owner,"failure","smelt "+item+": "+e.message,3);return false}}
  async harvest(){const crops=new Set(["wheat","carrots","potatoes","beetroots","nether_wart","sweet_berry_bush","cocoa"]);const positions=this.bot.findBlocks({matching:b=>b&&crops.has(b.name),maxDistance:32,count:24});let done=0;for(const p of positions){const b=this.bot.blockAt(p);if(!b)continue;try{await this.bot.dig(b);done++}catch{}}this.lastAction="harvested "+done+" crops";return done>0}
  async farm(){await this.harvest();const seeds=this.bot.inventory.items().find(i=>["wheat_seeds","carrot","potato","beetroot_seeds"].includes(i.name));if(!seeds)return false;const soil=this.bot.findBlock({matching:b=>b?.name==="farmland",maxDistance:24});if(!soil)return false;try{await this.bot.equip(seeds,"hand");await this.bot.pathfinder.goto(new GoalNear(soil.position.x,soil.position.y,soil.position.z,2));return true}catch{return false}}
  async build(blockName="oak_planks",pattern="wall"){const item=this.bot.inventory.items().find(i=>i.name===blockName);if(!item)return false;const base=this.bot.entity.position.floored(),positions=[];if(pattern==="floor"){for(let x=-2;x<=2;x++)for(let z=-2;z<=2;z++)positions.push(base.offset(x,-1,z));}else{for(let y=0;y<3;y++)for(let x=-2;x<=2;x++)positions.push(base.offset(x,y,4));}let placed=0;await this.bot.equip(item,"hand");for(const pos of positions){const b=this.bot.blockAt(pos),ref=this.bot.blockAt(pos.offset(0,-1,0));if(!b||b.name!=="air"||!ref||ref.name==="air")continue;try{await this.bot.placeBlock(ref,{x:0,y:1,z:0});placed++;if(placed>=item.count)break}catch{}}this.lastAction="built "+placed+" blocks";return placed>0}
  async store(){const chest=this.bot.findBlock({matching:b=>b&&(b.name==="chest"||b.name==="barrel"),maxDistance:12});if(!chest)return false;try{const w=await this.bot.openContainer(chest);for(const i of this.bot.inventory.items()){if(["diamond","emerald","iron_ingot","gold_ingot","coal","redstone","lapis_lazuli"].includes(i.name))await w.deposit(i.type,null,i.count).catch(()=>{})}w.close();this.lastAction="stored valuables";return true}catch{return false}}
  async sleep(){const bed=this.bot.findBlock({matching:b=>b&&b.name.endsWith("_bed"),maxDistance:24});if(!bed)return false;try{await this.bot.sleep(bed);this.lastAction="slept";return true}catch{return false}}
  avoid(){const p=this.bot.entity?.position;if(!p)return false;const danger=Object.values(this.bot.entities||{}).find(e=>e?.position&&DANGER.has(e.name)&&p.distanceTo(e.position)<8);if(!danger)return false;const dx=p.x-danger.position.x,dz=p.z-danger.position.z,len=Math.hypot(dx,dz)||1;this.goto(p.x+dx/len*12,p.y,p.z+dz/len*12);this.lastAction="moved away from danger";return true}
  explore(){const p=this.bot.entity?.position;if(!p)return false;const a=Math.random()*Math.PI*2,d=32+Math.random()*64;return this.goto(Math.floor(p.x+Math.cos(a)*d),Math.floor(p.y),Math.floor(p.z+Math.sin(a)*d))}
  async action(s){switch(s?.action){case"follow_owner":return this.follow(this.config.owner);case"come_owner":return this.come(this.config.owner);case"stop":this.stop();return true;case"goto":return this.goto(s.x,s.y,s.z);case"explore":return this.explore();case"avoid":return this.avoid();case"mine":case"collect":return this.collect(s.item||"stone",s.count||4);case"craft":return this.craft(s.item,s.count||1);case"smelt":return this.smelt(s.item,s.count||1);case"farm":return this.farm();case"harvest":return this.harvest();case"build":return this.build(s.block||"oak_planks",s.pattern||"wall");case"store":return this.store();case"sleep":return this.sleep();case"eat":return this.eat();default:return true}}
}